language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:    
    - 3.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yml
    - source activate differentiable_sorting
    
script: pytest    